name: Deploy package

concurrency:
  group: deploy

on:
  push:
    branches:
      - master

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_DEVELOPMENT }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_DEVELOPMENT }}
  AWS_DEFAULT_REGION: 'eu-west-1'
  AWS_DEFAULT_OUTPUT: 'text'
  PNPM_VERSION: '6.30.1'
  NODE_VERSION: '16.15'
  DEPLOY_DIR: 'dev'
  BASTION_KEY: ${{ secrets.AWS_BASTION_PRIVATE_KEY_DEVELOPMENT }}
  BASTION_DNS: 'ec2-54-229-18-90.eu-west-1.compute.amazonaws.com'
  DATABASE_DNS: 'dev-happenee.cu1trq40grim.eu-west-1.rds.amazonaws.com'
  DATABASE_LOCAL_PORT: '3306'
  ENVIRONMENT: 'development'
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
  DOCKER_BUILDKIT: '1'
  APP_VERSION: 'not-set' # set by calling scripts/get-release-version.ts

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm ci 

      - name: Run tests
        run: |
          npm run test

      - name: Run build
        run: |
          npm run build

      - name: Publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_PUBLISH_TOKEN }}
          access: "public"